### ISSUE TITLE
Only flash output?

### ISSUE THREAD

**Issue by fullofcaffeine** [jasonsturges/openfl-away3d-terrain-demo#1]
Hi!

Thanks for the demo and for releasing the source code, looks great!

I don't know much about Away3D or its Haxe port, but I was expecting it to also work on hxcpp, but looks like it doesn't. Is it something that will be restricted to SWF output?

Cheers!

**Comment by jasonsturges** [comment]
Hi, indeed - currently only the Flash target is operational, which is disappointing, I know.

Other targets are not ready yet.  Thanks for checking it out.

**Comment by fritzvd** [comment]
Hi @jasonsturges,

Too bad, although understandable with away3d. Do you know anything about openfl versions? Is there a specific one I need to target?

Fritz

**Comment by jasonsturges** [comment]
@fritzvd Hi, this should work with OpenFL 2._x_ or later, I'd presume.  I'm using OpenFL 2.2.4.

Not entirely sure what's up with Away3D issues cross-platform - I'll have to get back to you on that.

**Comment by fritzvd** [comment]
Interesting, it won't build with 2.2.4 but it will with 3.x
With removing this one line .. oh wait.. you just made it conditional :) :+1: 

Anyways, I'm building on all platforms now with a consistent build always showing this:

![terrain](https://cloud.githubusercontent.com/assets/160328/9515120/8ae6c104-4c9f-11e5-9630-5c0b188f8615.png)

**Comment by jasonsturges** [comment]
@fritzvd Yeah, non-Flash targets show the empty view.

Work to resolve issues with other targets is still in progress.

**Comment by jasonsturges** [comment]
@fullofcaffeine, @fritzvd Pull updates from this repo and Away3D, and html5 support is working.

Use:
- lime: [2.6.1]
- openfl: [3.3.2]

Demo: http://labs.jasonsturges.com/openfl/openfl-away3d-terrain-demo/html5/

Mac target is still in progress.

**Comment by jasonsturges** [comment]
Cool, and there's mac target; although, with some issues yet to be resolved.

![screen-capture](http://labs.jasonsturges.com/openfl/openfl-away3d-terrain-demo/openfl-away3d-terrain-mac-demo.jpg)

**Comment by fritzvd** [comment]
Cool!
